// Generated by piko.Generator
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
namespace piko.VulkanMemoryAllocator;
public static unsafe partial class VMA
{
    public enum AllocatorCreateFlagBits : uint
    {
        AllocatorCreateExternallySynchronizedBit = 0x00000001,
        AllocatorCreateKhrDedicatedAllocationBit = 0x00000002,
        AllocatorCreateKhrBindMemory2Bit = 0x00000004,
        AllocatorCreateExtMemoryBudgetBit = 0x00000008,
        AllocatorCreateAmdDeviceCoherentMemoryBit = 0x00000010,
        AllocatorCreateBufferDeviceAddressBit = 0x00000020,
        AllocatorCreateExtMemoryPriorityBit = 0x00000040,
        AllocatorCreateKhrMaintenance4Bit = 0x00000080,
        AllocatorCreateKhrMaintenance5Bit = 0x00000100,
        AllocatorCreateKhrExternalMemoryWin32Bit = 0x00000200,
        MaxEnum = 0x7fffffff,
    }
}
