// Generated by piko.Generator
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
namespace piko.VulkanMemoryAllocator;
[StructLayout(LayoutKind.Sequential)]
public unsafe struct AllocatorInfo
{
    public global::Silk.NET.Vulkan.Instance Instance;
    public global::Silk.NET.Vulkan.PhysicalDevice PhysicalDevice;
    public global::Silk.NET.Vulkan.Device Device;

    public AllocatorInfo(global::Silk.NET.Vulkan.Instance instance, global::Silk.NET.Vulkan.PhysicalDevice physicalDevice, global::Silk.NET.Vulkan.Device device)
    {
        this.Instance = instance;
        this.PhysicalDevice = physicalDevice;
        this.Device = device;
    }
}