// Generated by piko.Generator
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
namespace piko.VulkanMemoryAllocator;
public enum AllocationCreateFlagBits : uint
{
    DedicatedMemoryBit = 0x00000001,
    NeverAllocateBit = 0x00000002,
    MappedBit = 0x00000004,
    UserDataCopyStringBit = 0x00000020,
    UpperAddressBit = 0x00000040,
    DontBindBit = 0x00000080,
    WithinBudgetBit = 0x00000100,
    CanAliasBit = 0x00000200,
    HostAccessSequentialWriteBit = 0x00000400,
    HostAccessRandomBit = 0x00000800,
    HostAccessAllowTransferInsteadBit = 0x00001000,
    StrategyMinMemoryBit = 0x00010000,
    StrategyMinTimeBit = 0x00020000,
    StrategyMinOffsetBit = 0x00040000,
    StrategyBestFitBit = StrategyMinMemoryBit,
    StrategyFirstFitBit = StrategyMinTimeBit,
    StrategyMask = StrategyMinMemoryBit | vmaAllocationCreateStrategyMinTimeBit | vmaAllocationCreateStrategyMinOffsetBit,
    FlagBitsMaxEnum = 0x7fffffff,
}