// Generated by piko.Generator
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
namespace piko.VulkanMemoryAllocator;
[StructLayout(LayoutKind.Sequential)]
public unsafe struct AllocationInfo
{
    public uint MemoryType;
    public global::Silk.NET.Vulkan.DeviceMemory DeviceMemory;
    public ulong Offset;
    public ulong Size;
    public nint PMappedData;
    public nint PUserData;
    public sbyte* PName;

    public AllocationInfo(uint memoryType, global::Silk.NET.Vulkan.DeviceMemory deviceMemory, ulong offset, ulong size, nint pMappedData, nint pUserData, sbyte* pName)
    {
        this.MemoryType = memoryType;
        this.DeviceMemory = deviceMemory;
        this.Offset = offset;
        this.Size = size;
        this.PMappedData = pMappedData;
        this.PUserData = pUserData;
        this.PName = pName;
    }
}