// Generated by piko.Generator
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
namespace piko.VulkanMemoryAllocator;
[StructLayout(LayoutKind.Sequential)]
public unsafe struct Budget
{
    public Statistics Statistics;
    public ulong Usage;
    public ulong BudgetCount;

    public Budget(Statistics statistics, ulong usage, ulong budgetCount)
    {
        this.Statistics = statistics;
        this.Usage = usage;
        this.BudgetCount = budgetCount;
    }
}