// Generated by piko.Generator
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
namespace piko.VulkanMemoryAllocator;
public static unsafe partial class VMA
{
    [StructLayout(LayoutKind.Sequential)]
    public unsafe struct DefragmentationMove
    {
        public DefragmentationMoveOperation Operation;
        public AllocationT SrcAllocation;
        public AllocationT DstTmpAllocation;
    
        public DefragmentationMove(DefragmentationMoveOperation operation, AllocationT srcAllocation, AllocationT dstTmpAllocation)
        {
            this.Operation = operation;
            this.SrcAllocation = srcAllocation;
            this.DstTmpAllocation = dstTmpAllocation;
        }
    }
}
