// Generated by piko.Generator
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
namespace piko.VulkanMemoryAllocator;
public enum DefragmentationMoveOperation : uint
{
    Copy = 0,
    Ignore = 1,
    Destroy = 2,
}