// Generated by piko.Generator
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
namespace piko.VulkanMemoryAllocator;
[StructLayout(LayoutKind.Sequential)]
public unsafe struct DefragmentationInfo
{
    public uint Flags;
    public Pool Pool;
    public ulong MaxBytesPerPass;
    public uint MaxAllocationsPerPass;
    public IntPtr PfnBreakCallback;
    public nint PBreakCallbackUserData;

    public DefragmentationInfo(uint flags, Pool pool, ulong maxBytesPerPass, uint maxAllocationsPerPass, IntPtr pfnBreakCallback, nint pBreakCallbackUserData)
    {
        this.Flags = flags;
        this.Pool = pool;
        this.MaxBytesPerPass = maxBytesPerPass;
        this.MaxAllocationsPerPass = maxAllocationsPerPass;
        this.PfnBreakCallback = pfnBreakCallback;
        this.PBreakCallbackUserData = pBreakCallbackUserData;
    }
}