// Generated by piko.Generator
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
namespace piko.VulkanMemoryAllocator;
[StructLayout(LayoutKind.Sequential)]
public unsafe struct DefragmentationContext : piko.Core.IHandle
{
    private readonly nint _handle;

    public nint Handle => _handle;
    public bool IsNull => _handle == 0;

    public DefragmentationContext(nint handle)
    {
        _handle = handle;
    }
}