// Generated by piko.Generator
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
namespace piko.VulkanMemoryAllocator;
public enum DefragmentationFlagBits : uint
{
    AlgorithmFastBit = 0x1,
    AlgorithmBalancedBit = 0x2,
    AlgorithmFullBit = 0x4,
    AlgorithmExtensiveBit = 0x8,
    AlgorithmMask = AlgorithmFastBit | AlgorithmBalancedBit | AlgorithmFullBit | AlgorithmExtensiveBit,
    BitsMaxEnum = 0x7fffffff,
}