// Generated by piko.Generator
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
namespace piko.VulkanMemoryAllocator;
public static unsafe partial class VMA
{
    [StructLayout(LayoutKind.Sequential)]
    public unsafe struct DefragmentationInfo
    {
        public uint Flags;
        public PoolT Pool;
        public ulong MaxBytesPerPass;
        public uint MaxAllocationsPerPass;
        public IntPtr PfnBreakCallback;
        public void* PBreakCallbackUserData;
    
        public DefragmentationInfo(uint flags, PoolT pool, ulong maxBytesPerPass, uint maxAllocationsPerPass, IntPtr pfnBreakCallback, void* pBreakCallbackUserData)
        {
            this.Flags = flags;
            this.Pool = pool;
            this.MaxBytesPerPass = maxBytesPerPass;
            this.MaxAllocationsPerPass = maxAllocationsPerPass;
            this.PfnBreakCallback = pfnBreakCallback;
            this.PBreakCallbackUserData = pBreakCallbackUserData;
        }
    }
}
