// Generated by piko.Generator
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
namespace piko.VulkanMemoryAllocator;
[StructLayout(LayoutKind.Sequential)]
public unsafe struct DefragmentationMove
{
    public DefragmentationMoveOperation Operation;
    public Allocation SrcAllocation;
    public Allocation DstTmpAllocation;

    public DefragmentationMove(DefragmentationMoveOperation operation, Allocation srcAllocation, Allocation dstTmpAllocation)
    {
        this.Operation = operation;
        this.SrcAllocation = srcAllocation;
        this.DstTmpAllocation = dstTmpAllocation;
    }
}