// Generated by piko.Generator
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
namespace piko.VulkanMemoryAllocator;
[StructLayout(LayoutKind.Sequential)]
public unsafe struct DefragmentationPassMoveInfo
{
    public uint MoveCount;
    public DefragmentationMove* PMoves;

    public DefragmentationPassMoveInfo(uint moveCount, DefragmentationMove* pMoves)
    {
        this.MoveCount = moveCount;
        this.PMoves = pMoves;
    }
}