// Generated by piko.Generator
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
namespace piko.VulkanMemoryAllocator;
public static unsafe partial class VMA
{
    public enum DefragmentationFlagBits : uint
    {
        DefragmentationFlagAlgorithmFastBit = 0x1,
        DefragmentationFlagAlgorithmBalancedBit = 0x2,
        DefragmentationFlagAlgorithmFullBit = 0x4,
        DefragmentationFlagAlgorithmExtensiveBit = 0x8,
        DefragmentationFlagAlgorithmMask = DefragmentationFlagAlgorithmFastBit | vmaDefragmentationFlagAlgorithmBalancedBit | vmaDefragmentationFlagAlgorithmFullBit | vmaDefragmentationFlagAlgorithmExtensiveBit,
        MaxEnum = 0x7fffffff,
    }
}
