// Generated by piko.Generator
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
namespace piko.VulkanMemoryAllocator;
[StructLayout(LayoutKind.Sequential)]
public unsafe struct DeviceMemoryCallbacks
{
    public IntPtr PfnAllocate;
    public IntPtr PfnFree;
    public void* PUserData;

    public DeviceMemoryCallbacks(IntPtr pfnAllocate, IntPtr pfnFree, void* pUserData)
    {
        this.PfnAllocate = pfnAllocate;
        this.PfnFree = pfnFree;
        this.PUserData = pUserData;
    }
}