<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <RootNamespace>piko.VulkanMemoryAllocator</RootNamespace>
        <Description>A small n cute set of Vulkan Memory Allocator bindings for Silk.NET 2.x</Description>
        <PackageTags>$(PackageTags);vulkan;vma;vulkan memory allocator;silk;silk.net;silknet;silkdotnet</PackageTags>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Silk.NET.Vulkan" Version="2.*" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\piko.Core\piko.Core.csproj" />
    </ItemGroup>

    <ItemGroup>
        <None Include="runtimes/**/*" Pack="true" PackagePath="runtimes/" />
    </ItemGroup>

</Project>
