// Generated by piko.Generator
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
namespace piko.VulkanMemoryAllocator;
public static unsafe partial class VMA
{
    [StructLayout(LayoutKind.Sequential)]
    public unsafe struct PoolCreateInfo
    {
        public uint MemoryTypeIndex;
        public uint Flags;
        public ulong BlockSize;
        public nuint MinBlockCount;
        public nuint MaxBlockCount;
        public float Priority;
        public ulong MinAllocationAlignment;
        public void* PMemoryAllocateNext;
    
        public PoolCreateInfo(uint memoryTypeIndex, uint flags, ulong blockSize, nuint minBlockCount, nuint maxBlockCount, float priority, ulong minAllocationAlignment, void* pMemoryAllocateNext)
        {
            this.MemoryTypeIndex = memoryTypeIndex;
            this.Flags = flags;
            this.BlockSize = blockSize;
            this.MinBlockCount = minBlockCount;
            this.MaxBlockCount = maxBlockCount;
            this.Priority = priority;
            this.MinAllocationAlignment = minAllocationAlignment;
            this.PMemoryAllocateNext = pMemoryAllocateNext;
        }
    }
}
