// Generated by piko.Generator
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
namespace piko.VulkanMemoryAllocator;
public static unsafe partial class VMA
{
    public enum PoolCreateFlagBits : uint
    {
        PoolCreateIgnoreBufferImageGranularityBit = 0x00000002,
        PoolCreateLinearAlgorithmBit = 0x00000004,
        PoolCreateAlgorithmMask = PoolCreateLinearAlgorithmBit,
        MaxEnum = 0x7fffffff,
    }
}
