// Generated by piko.Generator
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
namespace piko.VulkanMemoryAllocator;
public enum PoolCreateFlagBits : uint
{
    IgnoreBufferImageGranularityBit = 0x00000002,
    LinearAlgorithmBit = 0x00000004,
    AlgorithmMask = LinearAlgorithmBit,
    FlagBitsMaxEnum = 0x7fffffff,
}