// Generated by piko.Generator
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
namespace piko.VulkanMemoryAllocator;
public static unsafe partial class VMA
{
    [StructLayout(LayoutKind.Sequential)]
    public unsafe struct TotalStatistics
    {
        public DetailedStatistics MemoryType;
        public DetailedStatistics MemoryHeap;
        public DetailedStatistics Total;
    
        public TotalStatistics(DetailedStatistics memoryType, DetailedStatistics memoryHeap, DetailedStatistics total)
        {
            this.MemoryType = memoryType;
            this.MemoryHeap = memoryHeap;
            this.Total = total;
        }
    }
}
