// Generated by piko.Generator
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
namespace piko.VulkanMemoryAllocator;
[StructLayout(LayoutKind.Sequential)]
public unsafe struct VirtualAllocationInfo
{
    public ulong Offset;
    public ulong Size;
    public void* PUserData;

    public VirtualAllocationInfo(ulong offset, ulong size, void* pUserData)
    {
        this.Offset = offset;
        this.Size = size;
        this.PUserData = pUserData;
    }
}