// Generated by piko.Generator
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
namespace piko.VulkanMemoryAllocator;
public enum VirtualAllocationCreateFlagBits : uint
{
    UpperAddressBit = AllocationCreateFlagBits.UpperAddressBit,
    StrategyMinMemoryBit = AllocationCreateFlagBits.StrategyMinMemoryBit,
    StrategyMinTimeBit = AllocationCreateFlagBits.StrategyMinTimeBit,
    StrategyMinOffsetBit = AllocationCreateFlagBits.StrategyMinOffsetBit,
    StrategyMask = AllocationCreateFlagBits.StrategyMask,
    FlagBitsMaxEnum = 0x7fffffff,
}