// Generated by piko.Generator
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
namespace piko.VulkanMemoryAllocator;
public static unsafe partial class VMA
{
    public enum VirtualBlockCreateFlagBits : uint
    {
        VirtualBlockCreateLinearAlgorithmBit = 0x00000001,
        VirtualBlockCreateAlgorithmMask = VirtualBlockCreateLinearAlgorithmBit,
        MaxEnum = 0x7fffffff,
    }
}
