// Generated by piko.Generator
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
namespace piko.VulkanMemoryAllocator;
public enum VirtualBlockCreateFlagBits : uint
{
    LinearAlgorithmBit = 0x00000001,
    AlgorithmMask = LinearAlgorithmBit,
    FlagBitsMaxEnum = 0x7fffffff,
}