// Generated by piko.Generator
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
namespace piko.VulkanMemoryAllocator;
public enum VirtualAllocationCreateFlagBits : uint
{
    UpperAddressBit = UpperAddressBit,
    StrategyMinMemoryBit = StrategyMinMemoryBit,
    StrategyMinTimeBit = StrategyMinTimeBit,
    StrategyMinOffsetBit = StrategyMinOffsetBit,
    StrategyMask = StrategyMask,
    FlagBitsMaxEnum = 0x7fffffff,
}