// Generated by piko.Generator
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
namespace piko.VulkanMemoryAllocator;
public static unsafe partial class VMA
{
    public enum VirtualAllocationCreateFlagBits : uint
    {
        VirtualAllocationCreateUpperAddressBit = AllocationCreateUpperAddressBit,
        VirtualAllocationCreateStrategyMinMemoryBit = AllocationCreateStrategyMinMemoryBit,
        VirtualAllocationCreateStrategyMinTimeBit = AllocationCreateStrategyMinTimeBit,
        VirtualAllocationCreateStrategyMinOffsetBit = AllocationCreateStrategyMinOffsetBit,
        VirtualAllocationCreateStrategyMask = AllocationCreateStrategyMask,
        MaxEnum = 0x7fffffff,
    }
}
