// Generated by piko.Generator
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
namespace piko.VulkanMemoryAllocator;
[StructLayout(LayoutKind.Sequential)]
public unsafe struct VirtualAllocationCreateInfo
{
    public ulong Size;
    public ulong Alignment;
    public uint Flags;
    public nint PUserData;

    public VirtualAllocationCreateInfo(ulong size, ulong alignment, uint flags, nint pUserData)
    {
        this.Size = size;
        this.Alignment = alignment;
        this.Flags = flags;
        this.PUserData = pUserData;
    }
}