// Generated by piko.Generator
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
namespace piko.VulkanMemoryAllocator;
public static unsafe partial class VMA
{
    public const string LibraryName = "VulkanMemoryAllocator";

    public const uint Version = (((((uint)(3)) << 22) | (((uint)(4)) << 12) | ((uint)(0))));
    public const int VulkanVersion = 1004000;
    public const int DedicatedAllocation = 1;
    public const int BindMemory2 = 1;
    public const int GetPhysicalDeviceProperties2 = 1;
    public const int MemoryBudget = 1;
    public const int BufferDeviceAddress = 1;
    public const int MemoryPriority = 1;
    public const int KhrMaintenance4 = 1;
    public const int KhrMaintenance5 = 1;
    public const int ExternalMemory = 1;
    public const int ExternalMemoryWin32 = 0;
    public const int StatsStringEnabled = 1;

    [DllImport(LibraryName, EntryPoint = "vmaCreateAllocator")]
    public static extern global::Silk.NET.Vulkan.Result CreateAllocator(AllocatorCreateInfo* pcreateinfo, Allocator* pallocator);

    [DllImport(LibraryName, EntryPoint = "vmaDestroyAllocator")]
    public static extern void DestroyAllocator(Allocator allocator);

    [DllImport(LibraryName, EntryPoint = "vmaGetAllocatorInfo")]
    public static extern void GetAllocatorInfo(Allocator allocator, AllocatorInfo* pallocatorinfo);

    [DllImport(LibraryName, EntryPoint = "vmaGetPhysicalDeviceProperties")]
    public static extern void GetPhysicalDeviceProperties(Allocator allocator, global::Silk.NET.Vulkan.PhysicalDeviceProperties** ppphysicaldeviceproperties);

    [DllImport(LibraryName, EntryPoint = "vmaGetMemoryProperties")]
    public static extern void GetMemoryProperties(Allocator allocator, global::Silk.NET.Vulkan.PhysicalDeviceMemoryProperties** ppphysicaldevicememoryproperties);

    [DllImport(LibraryName, EntryPoint = "vmaGetMemoryTypeProperties")]
    public static extern void GetMemoryTypeProperties(Allocator allocator, uint memorytypeindex, uint* pflags);

    [DllImport(LibraryName, EntryPoint = "vmaSetCurrentFrameIndex")]
    public static extern void SetCurrentFrameIndex(Allocator allocator, uint frameindex);

    [DllImport(LibraryName, EntryPoint = "vmaCalculateStatistics")]
    public static extern void CalculateStatistics(Allocator allocator, TotalStatistics* pstats);

    [DllImport(LibraryName, EntryPoint = "vmaGetHeapBudgets")]
    public static extern void GetHeapBudgets(Allocator allocator, Budget* pbudgets);

    [DllImport(LibraryName, EntryPoint = "vmaFindMemoryTypeIndex")]
    public static extern global::Silk.NET.Vulkan.Result FindMemoryTypeIndex(Allocator allocator, uint memorytypebits, AllocationCreateInfo* pallocationcreateinfo, uint* pmemorytypeindex);

    [DllImport(LibraryName, EntryPoint = "vmaFindMemoryTypeIndexForBufferInfo")]
    public static extern global::Silk.NET.Vulkan.Result FindMemoryTypeIndexForBufferInfo(Allocator allocator, global::Silk.NET.Vulkan.BufferCreateInfo* pbuffercreateinfo, AllocationCreateInfo* pallocationcreateinfo, uint* pmemorytypeindex);

    [DllImport(LibraryName, EntryPoint = "vmaFindMemoryTypeIndexForImageInfo")]
    public static extern global::Silk.NET.Vulkan.Result FindMemoryTypeIndexForImageInfo(Allocator allocator, global::Silk.NET.Vulkan.ImageCreateInfo* pimagecreateinfo, AllocationCreateInfo* pallocationcreateinfo, uint* pmemorytypeindex);

    [DllImport(LibraryName, EntryPoint = "vmaCreatePool")]
    public static extern global::Silk.NET.Vulkan.Result CreatePool(Allocator allocator, PoolCreateInfo* pcreateinfo, Pool* ppool);

    [DllImport(LibraryName, EntryPoint = "vmaDestroyPool")]
    public static extern void DestroyPool(Allocator allocator, Pool pool);

    [DllImport(LibraryName, EntryPoint = "vmaGetPoolStatistics")]
    public static extern void GetPoolStatistics(Allocator allocator, Pool pool, Statistics* ppoolstats);

    [DllImport(LibraryName, EntryPoint = "vmaCalculatePoolStatistics")]
    public static extern void CalculatePoolStatistics(Allocator allocator, Pool pool, DetailedStatistics* ppoolstats);

    [DllImport(LibraryName, EntryPoint = "vmaCheckPoolCorruption")]
    public static extern global::Silk.NET.Vulkan.Result CheckPoolCorruption(Allocator allocator, Pool pool);

    [DllImport(LibraryName, EntryPoint = "vmaGetPoolName")]
    public static extern void GetPoolName(Allocator allocator, Pool pool, sbyte** ppname);

    [DllImport(LibraryName, EntryPoint = "vmaSetPoolName")]
    public static extern void SetPoolName(Allocator allocator, Pool pool, string pname);

    [DllImport(LibraryName, EntryPoint = "vmaAllocateMemory")]
    public static extern global::Silk.NET.Vulkan.Result AllocateMemory(Allocator allocator, global::Silk.NET.Vulkan.MemoryRequirements* pvkmemoryrequirements, AllocationCreateInfo* pcreateinfo, Allocation* pallocation, AllocationInfo* pallocationinfo);

    [DllImport(LibraryName, EntryPoint = "vmaAllocateDedicatedMemory")]
    public static extern global::Silk.NET.Vulkan.Result AllocateDedicatedMemory(Allocator allocator, global::Silk.NET.Vulkan.MemoryRequirements* pvkmemoryrequirements, AllocationCreateInfo* pcreateinfo, nint pmemoryallocatenext, Allocation* pallocation, AllocationInfo* pallocationinfo);

    [DllImport(LibraryName, EntryPoint = "vmaAllocateMemoryPages")]
    public static extern global::Silk.NET.Vulkan.Result AllocateMemoryPages(Allocator allocator, global::Silk.NET.Vulkan.MemoryRequirements* pvkmemoryrequirements, AllocationCreateInfo* pcreateinfo, nuint allocationcount, Allocation* pallocations, AllocationInfo* pallocationinfo);

    [DllImport(LibraryName, EntryPoint = "vmaAllocateMemoryForBuffer")]
    public static extern global::Silk.NET.Vulkan.Result AllocateMemoryForBuffer(Allocator allocator, global::Silk.NET.Vulkan.Buffer buffer, AllocationCreateInfo* pcreateinfo, Allocation* pallocation, AllocationInfo* pallocationinfo);

    [DllImport(LibraryName, EntryPoint = "vmaAllocateMemoryForImage")]
    public static extern global::Silk.NET.Vulkan.Result AllocateMemoryForImage(Allocator allocator, global::Silk.NET.Vulkan.Image image, AllocationCreateInfo* pcreateinfo, Allocation* pallocation, AllocationInfo* pallocationinfo);

    [DllImport(LibraryName, EntryPoint = "vmaFreeMemory")]
    public static extern void FreeMemory(Allocator allocator, Allocation allocation);

    [DllImport(LibraryName, EntryPoint = "vmaFreeMemoryPages")]
    public static extern void FreeMemoryPages(Allocator allocator, nuint allocationcount, Allocation* pallocations);

    [DllImport(LibraryName, EntryPoint = "vmaGetAllocationInfo")]
    public static extern void GetAllocationInfo(Allocator allocator, Allocation allocation, AllocationInfo* pallocationinfo);

    [DllImport(LibraryName, EntryPoint = "vmaGetAllocationInfo2")]
    public static extern void GetAllocationInfo2(Allocator allocator, Allocation allocation, AllocationInfo2* pallocationinfo);

    [DllImport(LibraryName, EntryPoint = "vmaSetAllocationUserData")]
    public static extern void SetAllocationUserData(Allocator allocator, Allocation allocation, nint puserdata);

    [DllImport(LibraryName, EntryPoint = "vmaSetAllocationName")]
    public static extern void SetAllocationName(Allocator allocator, Allocation allocation, string pname);

    [DllImport(LibraryName, EntryPoint = "vmaGetAllocationMemoryProperties")]
    public static extern void GetAllocationMemoryProperties(Allocator allocator, Allocation allocation, uint* pflags);

    [DllImport(LibraryName, EntryPoint = "vmaMapMemory")]
    public static extern global::Silk.NET.Vulkan.Result MapMemory(Allocator allocator, Allocation allocation, nint ppdata);

    [DllImport(LibraryName, EntryPoint = "vmaUnmapMemory")]
    public static extern void UnmapMemory(Allocator allocator, Allocation allocation);

    [DllImport(LibraryName, EntryPoint = "vmaFlushAllocation")]
    public static extern global::Silk.NET.Vulkan.Result FlushAllocation(Allocator allocator, Allocation allocation, ulong offset, ulong size);

    [DllImport(LibraryName, EntryPoint = "vmaInvalidateAllocation")]
    public static extern global::Silk.NET.Vulkan.Result InvalidateAllocation(Allocator allocator, Allocation allocation, ulong offset, ulong size);

    [DllImport(LibraryName, EntryPoint = "vmaFlushAllocations")]
    public static extern global::Silk.NET.Vulkan.Result FlushAllocations(Allocator allocator, uint allocationcount, Allocation* allocations, ulong* offsets, ulong* sizes);

    [DllImport(LibraryName, EntryPoint = "vmaInvalidateAllocations")]
    public static extern global::Silk.NET.Vulkan.Result InvalidateAllocations(Allocator allocator, uint allocationcount, Allocation* allocations, ulong* offsets, ulong* sizes);

    [DllImport(LibraryName, EntryPoint = "vmaCopyMemoryToAllocation")]
    public static extern global::Silk.NET.Vulkan.Result CopyMemoryToAllocation(Allocator allocator, nint psrchostpointer, Allocation dstallocation, ulong dstallocationlocaloffset, ulong size);

    [DllImport(LibraryName, EntryPoint = "vmaCopyAllocationToMemory")]
    public static extern global::Silk.NET.Vulkan.Result CopyAllocationToMemory(Allocator allocator, Allocation srcallocation, ulong srcallocationlocaloffset, nint pdsthostpointer, ulong size);

    [DllImport(LibraryName, EntryPoint = "vmaCheckCorruption")]
    public static extern global::Silk.NET.Vulkan.Result CheckCorruption(Allocator allocator, uint memorytypebits);

    [DllImport(LibraryName, EntryPoint = "vmaBeginDefragmentation")]
    public static extern global::Silk.NET.Vulkan.Result BeginDefragmentation(Allocator allocator, DefragmentationInfo* pinfo, DefragmentationContext* pcontext);

    [DllImport(LibraryName, EntryPoint = "vmaEndDefragmentation")]
    public static extern void EndDefragmentation(Allocator allocator, DefragmentationContext context, DefragmentationStats* pstats);

    [DllImport(LibraryName, EntryPoint = "vmaBeginDefragmentationPass")]
    public static extern global::Silk.NET.Vulkan.Result BeginDefragmentationPass(Allocator allocator, DefragmentationContext context, DefragmentationPassMoveInfo* ppassinfo);

    [DllImport(LibraryName, EntryPoint = "vmaEndDefragmentationPass")]
    public static extern global::Silk.NET.Vulkan.Result EndDefragmentationPass(Allocator allocator, DefragmentationContext context, DefragmentationPassMoveInfo* ppassinfo);

    [DllImport(LibraryName, EntryPoint = "vmaBindBufferMemory")]
    public static extern global::Silk.NET.Vulkan.Result BindBufferMemory(Allocator allocator, Allocation allocation, global::Silk.NET.Vulkan.Buffer buffer);

    [DllImport(LibraryName, EntryPoint = "vmaBindBufferMemory2")]
    public static extern global::Silk.NET.Vulkan.Result BindBufferMemory2(Allocator allocator, Allocation allocation, ulong allocationlocaloffset, global::Silk.NET.Vulkan.Buffer buffer, nint pnext);

    [DllImport(LibraryName, EntryPoint = "vmaBindImageMemory")]
    public static extern global::Silk.NET.Vulkan.Result BindImageMemory(Allocator allocator, Allocation allocation, global::Silk.NET.Vulkan.Image image);

    [DllImport(LibraryName, EntryPoint = "vmaBindImageMemory2")]
    public static extern global::Silk.NET.Vulkan.Result BindImageMemory2(Allocator allocator, Allocation allocation, ulong allocationlocaloffset, global::Silk.NET.Vulkan.Image image, nint pnext);

    [DllImport(LibraryName, EntryPoint = "vmaCreateBuffer")]
    public static extern global::Silk.NET.Vulkan.Result CreateBuffer(Allocator allocator, global::Silk.NET.Vulkan.BufferCreateInfo* pbuffercreateinfo, AllocationCreateInfo* pallocationcreateinfo, global::Silk.NET.Vulkan.Buffer* pbuffer, Allocation* pallocation, AllocationInfo* pallocationinfo);

    [DllImport(LibraryName, EntryPoint = "vmaCreateBufferWithAlignment")]
    public static extern global::Silk.NET.Vulkan.Result CreateBufferWithAlignment(Allocator allocator, global::Silk.NET.Vulkan.BufferCreateInfo* pbuffercreateinfo, AllocationCreateInfo* pallocationcreateinfo, ulong minalignment, global::Silk.NET.Vulkan.Buffer* pbuffer, Allocation* pallocation, AllocationInfo* pallocationinfo);

    [DllImport(LibraryName, EntryPoint = "vmaCreateDedicatedBuffer")]
    public static extern global::Silk.NET.Vulkan.Result CreateDedicatedBuffer(Allocator allocator, global::Silk.NET.Vulkan.BufferCreateInfo* pbuffercreateinfo, AllocationCreateInfo* pallocationcreateinfo, nint pmemoryallocatenext, global::Silk.NET.Vulkan.Buffer* pbuffer, Allocation* pallocation, AllocationInfo* pallocationinfo);

    [DllImport(LibraryName, EntryPoint = "vmaCreateAliasingBuffer")]
    public static extern global::Silk.NET.Vulkan.Result CreateAliasingBuffer(Allocator allocator, Allocation allocation, global::Silk.NET.Vulkan.BufferCreateInfo* pbuffercreateinfo, global::Silk.NET.Vulkan.Buffer* pbuffer);

    [DllImport(LibraryName, EntryPoint = "vmaCreateAliasingBuffer2")]
    public static extern global::Silk.NET.Vulkan.Result CreateAliasingBuffer2(Allocator allocator, Allocation allocation, ulong allocationlocaloffset, global::Silk.NET.Vulkan.BufferCreateInfo* pbuffercreateinfo, global::Silk.NET.Vulkan.Buffer* pbuffer);

    [DllImport(LibraryName, EntryPoint = "vmaDestroyBuffer")]
    public static extern void DestroyBuffer(Allocator allocator, global::Silk.NET.Vulkan.Buffer buffer, Allocation allocation);

    [DllImport(LibraryName, EntryPoint = "vmaCreateImage")]
    public static extern global::Silk.NET.Vulkan.Result CreateImage(Allocator allocator, global::Silk.NET.Vulkan.ImageCreateInfo* pimagecreateinfo, AllocationCreateInfo* pallocationcreateinfo, global::Silk.NET.Vulkan.Image* pimage, Allocation* pallocation, AllocationInfo* pallocationinfo);

    [DllImport(LibraryName, EntryPoint = "vmaCreateDedicatedImage")]
    public static extern global::Silk.NET.Vulkan.Result CreateDedicatedImage(Allocator allocator, global::Silk.NET.Vulkan.ImageCreateInfo* pimagecreateinfo, AllocationCreateInfo* pallocationcreateinfo, nint pmemoryallocatenext, global::Silk.NET.Vulkan.Image* pimage, Allocation* pallocation, AllocationInfo* pallocationinfo);

    [DllImport(LibraryName, EntryPoint = "vmaCreateAliasingImage")]
    public static extern global::Silk.NET.Vulkan.Result CreateAliasingImage(Allocator allocator, Allocation allocation, global::Silk.NET.Vulkan.ImageCreateInfo* pimagecreateinfo, global::Silk.NET.Vulkan.Image* pimage);

    [DllImport(LibraryName, EntryPoint = "vmaCreateAliasingImage2")]
    public static extern global::Silk.NET.Vulkan.Result CreateAliasingImage2(Allocator allocator, Allocation allocation, ulong allocationlocaloffset, global::Silk.NET.Vulkan.ImageCreateInfo* pimagecreateinfo, global::Silk.NET.Vulkan.Image* pimage);

    [DllImport(LibraryName, EntryPoint = "vmaDestroyImage")]
    public static extern void DestroyImage(Allocator allocator, global::Silk.NET.Vulkan.Image image, Allocation allocation);

    [DllImport(LibraryName, EntryPoint = "vmaCreateVirtualBlock")]
    public static extern global::Silk.NET.Vulkan.Result CreateVirtualBlock(VirtualBlockCreateInfo* pcreateinfo, VirtualBlock* pvirtualblock);

    [DllImport(LibraryName, EntryPoint = "vmaDestroyVirtualBlock")]
    public static extern void DestroyVirtualBlock(VirtualBlock virtualblock);

    [DllImport(LibraryName, EntryPoint = "vmaIsVirtualBlockEmpty")]
    public static extern uint IsVirtualBlockEmpty(VirtualBlock virtualblock);

    [DllImport(LibraryName, EntryPoint = "vmaGetVirtualAllocationInfo")]
    public static extern void GetVirtualAllocationInfo(VirtualBlock virtualblock, VirtualAllocation allocation, VirtualAllocationInfo* pvirtualallocinfo);

    [DllImport(LibraryName, EntryPoint = "vmaVirtualAllocate")]
    public static extern global::Silk.NET.Vulkan.Result VirtualAllocate(VirtualBlock virtualblock, VirtualAllocationCreateInfo* pcreateinfo, VirtualAllocation* pallocation, ulong* poffset);

    [DllImport(LibraryName, EntryPoint = "vmaVirtualFree")]
    public static extern void VirtualFree(VirtualBlock virtualblock, VirtualAllocation allocation);

    [DllImport(LibraryName, EntryPoint = "vmaClearVirtualBlock")]
    public static extern void ClearVirtualBlock(VirtualBlock virtualblock);

    [DllImport(LibraryName, EntryPoint = "vmaSetVirtualAllocationUserData")]
    public static extern void SetVirtualAllocationUserData(VirtualBlock virtualblock, VirtualAllocation allocation, nint puserdata);

    [DllImport(LibraryName, EntryPoint = "vmaGetVirtualBlockStatistics")]
    public static extern void GetVirtualBlockStatistics(VirtualBlock virtualblock, Statistics* pstats);

    [DllImport(LibraryName, EntryPoint = "vmaCalculateVirtualBlockStatistics")]
    public static extern void CalculateVirtualBlockStatistics(VirtualBlock virtualblock, DetailedStatistics* pstats);

    [DllImport(LibraryName, EntryPoint = "vmaBuildVirtualBlockStatsString")]
    public static extern void BuildVirtualBlockStatsString(VirtualBlock virtualblock, sbyte** ppstatsstring, uint detailedmap);

    [DllImport(LibraryName, EntryPoint = "vmaFreeVirtualBlockStatsString")]
    public static extern void FreeVirtualBlockStatsString(VirtualBlock virtualblock, string pstatsstring);

    [DllImport(LibraryName, EntryPoint = "vmaBuildStatsString")]
    public static extern void BuildStatsString(Allocator allocator, sbyte** ppstatsstring, uint detailedmap);

    [DllImport(LibraryName, EntryPoint = "vmaFreeStatsString")]
    public static extern void FreeStatsString(Allocator allocator, string pstatsstring);


    public delegate void PFNVmaAllocateDeviceMemoryFunction(Allocator allocator, uint memorytype, global::Silk.NET.Vulkan.DeviceMemory memory, ulong size, nint puserdata);

    public delegate void PFNVmaFreeDeviceMemoryFunction(Allocator allocator, uint memorytype, global::Silk.NET.Vulkan.DeviceMemory memory, ulong size, nint puserdata);

    public delegate uint PFNVmaCheckDefragmentationBreakFunction(nint puserdata);

}
