// Generated by piko.Generator
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
namespace piko.VulkanMemoryAllocator;
public static unsafe partial class VMA
{
    public const string LibraryName = "VulkanMemoryAllocator";

    public const uint Version = (((((uint)(3)) << 22) | (((uint)(4)) << 12) | ((uint)(0))));
    public const int VulkanVersion = 1004000;
    public const int DedicatedAllocation = 1;
    public const int BindMemory2 = 1;
    public const int GetPhysicalDeviceProperties2 = 1;
    public const int MemoryBudget = 1;
    public const int BufferDeviceAddress = 1;
    public const int MemoryPriority = 1;
    public const int KhrMaintenance4 = 1;
    public const int KhrMaintenance5 = 1;
    public const int ExternalMemory = 1;
    public const int ExternalMemoryWin32 = 0;
    public const int StatsStringEnabled = 1;

    [DllImport(LibraryName, EntryPoint = "vmaCreateAllocator")]
    public static extern global::Silk.NET.Vulkan.Device CreateAllocator(AllocatorCreateInfo* pcreateinfo, AllocatorT* pallocator);

    [DllImport(LibraryName, EntryPoint = "vmaDestroyAllocator")]
    public static extern void DestroyAllocator(AllocatorT allocator);

    [DllImport(LibraryName, EntryPoint = "vmaGetAllocatorInfo")]
    public static extern void GetAllocatorInfo(AllocatorT allocator, AllocatorInfo* pallocatorinfo);

    [DllImport(LibraryName, EntryPoint = "vmaGetPhysicalDeviceProperties")]
    public static extern void GetPhysicalDeviceProperties(AllocatorT allocator, global::Silk.NET.Vulkan.PhysicalDeviceProperties** ppphysicaldeviceproperties);

    [DllImport(LibraryName, EntryPoint = "vmaGetMemoryProperties")]
    public static extern void GetMemoryProperties(AllocatorT allocator, global::Silk.NET.Vulkan.PhysicalDeviceMemoryProperties** ppphysicaldevicememoryproperties);

    [DllImport(LibraryName, EntryPoint = "vmaGetMemoryTypeProperties")]
    public static extern void GetMemoryTypeProperties(AllocatorT allocator, uint memorytypeindex, uint* pflags);

    [DllImport(LibraryName, EntryPoint = "vmaSetCurrentFrameIndex")]
    public static extern void SetCurrentFrameIndex(AllocatorT allocator, uint frameindex);

    [DllImport(LibraryName, EntryPoint = "vmaCalculateStatistics")]
    public static extern void CalculateStatistics(AllocatorT allocator, TotalStatistics* pstats);

    [DllImport(LibraryName, EntryPoint = "vmaGetHeapBudgets")]
    public static extern void GetHeapBudgets(AllocatorT allocator, Budget* pbudgets);

    [DllImport(LibraryName, EntryPoint = "vmaFindMemoryTypeIndex")]
    public static extern global::Silk.NET.Vulkan.Device FindMemoryTypeIndex(AllocatorT allocator, uint memorytypebits, AllocationCreateInfo* pallocationcreateinfo, uint* pmemorytypeindex);

    [DllImport(LibraryName, EntryPoint = "vmaFindMemoryTypeIndexForBufferInfo")]
    public static extern global::Silk.NET.Vulkan.Device FindMemoryTypeIndexForBufferInfo(AllocatorT allocator, global::Silk.NET.Vulkan.BufferCreateInfo* pbuffercreateinfo, AllocationCreateInfo* pallocationcreateinfo, uint* pmemorytypeindex);

    [DllImport(LibraryName, EntryPoint = "vmaFindMemoryTypeIndexForImageInfo")]
    public static extern global::Silk.NET.Vulkan.Device FindMemoryTypeIndexForImageInfo(AllocatorT allocator, global::Silk.NET.Vulkan.ImageCreateInfo* pimagecreateinfo, AllocationCreateInfo* pallocationcreateinfo, uint* pmemorytypeindex);

    [DllImport(LibraryName, EntryPoint = "vmaCreatePool")]
    public static extern global::Silk.NET.Vulkan.Device CreatePool(AllocatorT allocator, PoolCreateInfo* pcreateinfo, PoolT* ppool);

    [DllImport(LibraryName, EntryPoint = "vmaDestroyPool")]
    public static extern void DestroyPool(AllocatorT allocator, PoolT pool);

    [DllImport(LibraryName, EntryPoint = "vmaGetPoolStatistics")]
    public static extern void GetPoolStatistics(AllocatorT allocator, PoolT pool, Statistics* ppoolstats);

    [DllImport(LibraryName, EntryPoint = "vmaCalculatePoolStatistics")]
    public static extern void CalculatePoolStatistics(AllocatorT allocator, PoolT pool, DetailedStatistics* ppoolstats);

    [DllImport(LibraryName, EntryPoint = "vmaCheckPoolCorruption")]
    public static extern global::Silk.NET.Vulkan.Device CheckPoolCorruption(AllocatorT allocator, PoolT pool);

    [DllImport(LibraryName, EntryPoint = "vmaGetPoolName")]
    public static extern void GetPoolName(AllocatorT allocator, PoolT pool, sbyte** ppname);

    [DllImport(LibraryName, EntryPoint = "vmaSetPoolName")]
    public static extern void SetPoolName(AllocatorT allocator, PoolT pool, string pname);

    [DllImport(LibraryName, EntryPoint = "vmaAllocateMemory")]
    public static extern global::Silk.NET.Vulkan.Device AllocateMemory(AllocatorT allocator, global::Silk.NET.Vulkan.MemoryRequirements* pvkmemoryrequirements, AllocationCreateInfo* pcreateinfo, AllocationT* pallocation, AllocationInfo* pallocationinfo);

    [DllImport(LibraryName, EntryPoint = "vmaAllocateDedicatedMemory")]
    public static extern global::Silk.NET.Vulkan.Device AllocateDedicatedMemory(AllocatorT allocator, global::Silk.NET.Vulkan.MemoryRequirements* pvkmemoryrequirements, AllocationCreateInfo* pcreateinfo, void* pmemoryallocatenext, AllocationT* pallocation, AllocationInfo* pallocationinfo);

    [DllImport(LibraryName, EntryPoint = "vmaAllocateMemoryPages")]
    public static extern global::Silk.NET.Vulkan.Device AllocateMemoryPages(AllocatorT allocator, global::Silk.NET.Vulkan.MemoryRequirements* pvkmemoryrequirements, AllocationCreateInfo* pcreateinfo, nuint allocationcount, AllocationT* pallocations, AllocationInfo* pallocationinfo);

    [DllImport(LibraryName, EntryPoint = "vmaAllocateMemoryForBuffer")]
    public static extern global::Silk.NET.Vulkan.Device AllocateMemoryForBuffer(AllocatorT allocator, global::Silk.NET.Vulkan.Buffer* buffer, AllocationCreateInfo* pcreateinfo, AllocationT* pallocation, AllocationInfo* pallocationinfo);

    [DllImport(LibraryName, EntryPoint = "vmaAllocateMemoryForImage")]
    public static extern global::Silk.NET.Vulkan.Device AllocateMemoryForImage(AllocatorT allocator, global::Silk.NET.Vulkan.Image* image, AllocationCreateInfo* pcreateinfo, AllocationT* pallocation, AllocationInfo* pallocationinfo);

    [DllImport(LibraryName, EntryPoint = "vmaFreeMemory")]
    public static extern void FreeMemory(AllocatorT allocator, AllocationT allocation);

    [DllImport(LibraryName, EntryPoint = "vmaFreeMemoryPages")]
    public static extern void FreeMemoryPages(AllocatorT allocator, nuint allocationcount, AllocationT* pallocations);

    [DllImport(LibraryName, EntryPoint = "vmaGetAllocationInfo")]
    public static extern void GetAllocationInfo(AllocatorT allocator, AllocationT allocation, AllocationInfo* pallocationinfo);

    [DllImport(LibraryName, EntryPoint = "vmaGetAllocationInfo2")]
    public static extern void GetAllocationInfo2(AllocatorT allocator, AllocationT allocation, AllocationInfo2* pallocationinfo);

    [DllImport(LibraryName, EntryPoint = "vmaSetAllocationUserData")]
    public static extern void SetAllocationUserData(AllocatorT allocator, AllocationT allocation, void* puserdata);

    [DllImport(LibraryName, EntryPoint = "vmaSetAllocationName")]
    public static extern void SetAllocationName(AllocatorT allocator, AllocationT allocation, string pname);

    [DllImport(LibraryName, EntryPoint = "vmaGetAllocationMemoryProperties")]
    public static extern void GetAllocationMemoryProperties(AllocatorT allocator, AllocationT allocation, uint* pflags);

    [DllImport(LibraryName, EntryPoint = "vmaMapMemory")]
    public static extern global::Silk.NET.Vulkan.Device MapMemory(AllocatorT allocator, AllocationT allocation, void** ppdata);

    [DllImport(LibraryName, EntryPoint = "vmaUnmapMemory")]
    public static extern void UnmapMemory(AllocatorT allocator, AllocationT allocation);

    [DllImport(LibraryName, EntryPoint = "vmaFlushAllocation")]
    public static extern global::Silk.NET.Vulkan.Device FlushAllocation(AllocatorT allocator, AllocationT allocation, ulong offset, ulong size);

    [DllImport(LibraryName, EntryPoint = "vmaInvalidateAllocation")]
    public static extern global::Silk.NET.Vulkan.Device InvalidateAllocation(AllocatorT allocator, AllocationT allocation, ulong offset, ulong size);

    [DllImport(LibraryName, EntryPoint = "vmaFlushAllocations")]
    public static extern global::Silk.NET.Vulkan.Device FlushAllocations(AllocatorT allocator, uint allocationcount, AllocationT* allocations, ulong* offsets, ulong* sizes);

    [DllImport(LibraryName, EntryPoint = "vmaInvalidateAllocations")]
    public static extern global::Silk.NET.Vulkan.Device InvalidateAllocations(AllocatorT allocator, uint allocationcount, AllocationT* allocations, ulong* offsets, ulong* sizes);

    [DllImport(LibraryName, EntryPoint = "vmaCopyMemoryToAllocation")]
    public static extern global::Silk.NET.Vulkan.Device CopyMemoryToAllocation(AllocatorT allocator, void* psrchostpointer, AllocationT dstallocation, ulong dstallocationlocaloffset, ulong size);

    [DllImport(LibraryName, EntryPoint = "vmaCopyAllocationToMemory")]
    public static extern global::Silk.NET.Vulkan.Device CopyAllocationToMemory(AllocatorT allocator, AllocationT srcallocation, ulong srcallocationlocaloffset, void* pdsthostpointer, ulong size);

    [DllImport(LibraryName, EntryPoint = "vmaCheckCorruption")]
    public static extern global::Silk.NET.Vulkan.Device CheckCorruption(AllocatorT allocator, uint memorytypebits);

    [DllImport(LibraryName, EntryPoint = "vmaBeginDefragmentation")]
    public static extern global::Silk.NET.Vulkan.Device BeginDefragmentation(AllocatorT allocator, DefragmentationInfo* pinfo, DefragmentationContextT* pcontext);

    [DllImport(LibraryName, EntryPoint = "vmaEndDefragmentation")]
    public static extern void EndDefragmentation(AllocatorT allocator, DefragmentationContextT context, DefragmentationStats* pstats);

    [DllImport(LibraryName, EntryPoint = "vmaBeginDefragmentationPass")]
    public static extern global::Silk.NET.Vulkan.Device BeginDefragmentationPass(AllocatorT allocator, DefragmentationContextT context, DefragmentationPassMoveInfo* ppassinfo);

    [DllImport(LibraryName, EntryPoint = "vmaEndDefragmentationPass")]
    public static extern global::Silk.NET.Vulkan.Device EndDefragmentationPass(AllocatorT allocator, DefragmentationContextT context, DefragmentationPassMoveInfo* ppassinfo);

    [DllImport(LibraryName, EntryPoint = "vmaBindBufferMemory")]
    public static extern global::Silk.NET.Vulkan.Device BindBufferMemory(AllocatorT allocator, AllocationT allocation, global::Silk.NET.Vulkan.Buffer* buffer);

    [DllImport(LibraryName, EntryPoint = "vmaBindBufferMemory2")]
    public static extern global::Silk.NET.Vulkan.Device BindBufferMemory2(AllocatorT allocator, AllocationT allocation, ulong allocationlocaloffset, global::Silk.NET.Vulkan.Buffer* buffer, void* pnext);

    [DllImport(LibraryName, EntryPoint = "vmaBindImageMemory")]
    public static extern global::Silk.NET.Vulkan.Device BindImageMemory(AllocatorT allocator, AllocationT allocation, global::Silk.NET.Vulkan.Image* image);

    [DllImport(LibraryName, EntryPoint = "vmaBindImageMemory2")]
    public static extern global::Silk.NET.Vulkan.Device BindImageMemory2(AllocatorT allocator, AllocationT allocation, ulong allocationlocaloffset, global::Silk.NET.Vulkan.Image* image, void* pnext);

    [DllImport(LibraryName, EntryPoint = "vmaCreateBuffer")]
    public static extern global::Silk.NET.Vulkan.Device CreateBuffer(AllocatorT allocator, global::Silk.NET.Vulkan.BufferCreateInfo* pbuffercreateinfo, AllocationCreateInfo* pallocationcreateinfo, global::Silk.NET.Vulkan.Buffer** pbuffer, AllocationT* pallocation, AllocationInfo* pallocationinfo);

    [DllImport(LibraryName, EntryPoint = "vmaCreateBufferWithAlignment")]
    public static extern global::Silk.NET.Vulkan.Device CreateBufferWithAlignment(AllocatorT allocator, global::Silk.NET.Vulkan.BufferCreateInfo* pbuffercreateinfo, AllocationCreateInfo* pallocationcreateinfo, ulong minalignment, global::Silk.NET.Vulkan.Buffer** pbuffer, AllocationT* pallocation, AllocationInfo* pallocationinfo);

    [DllImport(LibraryName, EntryPoint = "vmaCreateDedicatedBuffer")]
    public static extern global::Silk.NET.Vulkan.Device CreateDedicatedBuffer(AllocatorT allocator, global::Silk.NET.Vulkan.BufferCreateInfo* pbuffercreateinfo, AllocationCreateInfo* pallocationcreateinfo, void* pmemoryallocatenext, global::Silk.NET.Vulkan.Buffer** pbuffer, AllocationT* pallocation, AllocationInfo* pallocationinfo);

    [DllImport(LibraryName, EntryPoint = "vmaCreateAliasingBuffer")]
    public static extern global::Silk.NET.Vulkan.Device CreateAliasingBuffer(AllocatorT allocator, AllocationT allocation, global::Silk.NET.Vulkan.BufferCreateInfo* pbuffercreateinfo, global::Silk.NET.Vulkan.Buffer** pbuffer);

    [DllImport(LibraryName, EntryPoint = "vmaCreateAliasingBuffer2")]
    public static extern global::Silk.NET.Vulkan.Device CreateAliasingBuffer2(AllocatorT allocator, AllocationT allocation, ulong allocationlocaloffset, global::Silk.NET.Vulkan.BufferCreateInfo* pbuffercreateinfo, global::Silk.NET.Vulkan.Buffer** pbuffer);

    [DllImport(LibraryName, EntryPoint = "vmaDestroyBuffer")]
    public static extern void DestroyBuffer(AllocatorT allocator, global::Silk.NET.Vulkan.Buffer* buffer, AllocationT allocation);

    [DllImport(LibraryName, EntryPoint = "vmaCreateImage")]
    public static extern global::Silk.NET.Vulkan.Device CreateImage(AllocatorT allocator, global::Silk.NET.Vulkan.ImageCreateInfo* pimagecreateinfo, AllocationCreateInfo* pallocationcreateinfo, global::Silk.NET.Vulkan.Image** pimage, AllocationT* pallocation, AllocationInfo* pallocationinfo);

    [DllImport(LibraryName, EntryPoint = "vmaCreateDedicatedImage")]
    public static extern global::Silk.NET.Vulkan.Device CreateDedicatedImage(AllocatorT allocator, global::Silk.NET.Vulkan.ImageCreateInfo* pimagecreateinfo, AllocationCreateInfo* pallocationcreateinfo, void* pmemoryallocatenext, global::Silk.NET.Vulkan.Image** pimage, AllocationT* pallocation, AllocationInfo* pallocationinfo);

    [DllImport(LibraryName, EntryPoint = "vmaCreateAliasingImage")]
    public static extern global::Silk.NET.Vulkan.Device CreateAliasingImage(AllocatorT allocator, AllocationT allocation, global::Silk.NET.Vulkan.ImageCreateInfo* pimagecreateinfo, global::Silk.NET.Vulkan.Image** pimage);

    [DllImport(LibraryName, EntryPoint = "vmaCreateAliasingImage2")]
    public static extern global::Silk.NET.Vulkan.Device CreateAliasingImage2(AllocatorT allocator, AllocationT allocation, ulong allocationlocaloffset, global::Silk.NET.Vulkan.ImageCreateInfo* pimagecreateinfo, global::Silk.NET.Vulkan.Image** pimage);

    [DllImport(LibraryName, EntryPoint = "vmaDestroyImage")]
    public static extern void DestroyImage(AllocatorT allocator, global::Silk.NET.Vulkan.Image* image, AllocationT allocation);

    [DllImport(LibraryName, EntryPoint = "vmaCreateVirtualBlock")]
    public static extern global::Silk.NET.Vulkan.Device CreateVirtualBlock(VirtualBlockCreateInfo* pcreateinfo, VirtualBlockT* pvirtualblock);

    [DllImport(LibraryName, EntryPoint = "vmaDestroyVirtualBlock")]
    public static extern void DestroyVirtualBlock(VirtualBlockT virtualblock);

    [DllImport(LibraryName, EntryPoint = "vmaIsVirtualBlockEmpty")]
    public static extern uint IsVirtualBlockEmpty(VirtualBlockT virtualblock);

    [DllImport(LibraryName, EntryPoint = "vmaGetVirtualAllocationInfo")]
    public static extern void GetVirtualAllocationInfo(VirtualBlockT virtualblock, VirtualAllocationT allocation, VirtualAllocationInfo* pvirtualallocinfo);

    [DllImport(LibraryName, EntryPoint = "vmaVirtualAllocate")]
    public static extern global::Silk.NET.Vulkan.Device VirtualAllocate(VirtualBlockT virtualblock, VirtualAllocationCreateInfo* pcreateinfo, VirtualAllocationT* pallocation, ulong* poffset);

    [DllImport(LibraryName, EntryPoint = "vmaVirtualFree")]
    public static extern void VirtualFree(VirtualBlockT virtualblock, VirtualAllocationT allocation);

    [DllImport(LibraryName, EntryPoint = "vmaClearVirtualBlock")]
    public static extern void ClearVirtualBlock(VirtualBlockT virtualblock);

    [DllImport(LibraryName, EntryPoint = "vmaSetVirtualAllocationUserData")]
    public static extern void SetVirtualAllocationUserData(VirtualBlockT virtualblock, VirtualAllocationT allocation, void* puserdata);

    [DllImport(LibraryName, EntryPoint = "vmaGetVirtualBlockStatistics")]
    public static extern void GetVirtualBlockStatistics(VirtualBlockT virtualblock, Statistics* pstats);

    [DllImport(LibraryName, EntryPoint = "vmaCalculateVirtualBlockStatistics")]
    public static extern void CalculateVirtualBlockStatistics(VirtualBlockT virtualblock, DetailedStatistics* pstats);

    [DllImport(LibraryName, EntryPoint = "vmaBuildVirtualBlockStatsString")]
    public static extern void BuildVirtualBlockStatsString(VirtualBlockT virtualblock, sbyte** ppstatsstring, uint detailedmap);

    [DllImport(LibraryName, EntryPoint = "vmaFreeVirtualBlockStatsString")]
    public static extern void FreeVirtualBlockStatsString(VirtualBlockT virtualblock, string pstatsstring);

    [DllImport(LibraryName, EntryPoint = "vmaBuildStatsString")]
    public static extern void BuildStatsString(AllocatorT allocator, sbyte** ppstatsstring, uint detailedmap);

    [DllImport(LibraryName, EntryPoint = "vmaFreeStatsString")]
    public static extern void FreeStatsString(AllocatorT allocator, string pstatsstring);


    public delegate void PFNVmaAllocateDeviceMemoryFunction(AllocatorT allocator, uint memorytype, global::Silk.NET.Vulkan.DeviceMemory* memory, ulong size, void* puserdata);

    public delegate void PFNVmaFreeDeviceMemoryFunction(AllocatorT allocator, uint memorytype, global::Silk.NET.Vulkan.DeviceMemory* memory, ulong size, void* puserdata);

    public delegate uint PFNVmaCheckDefragmentationBreakFunction(void* puserdata);

}
