// Generated by piko.Generator
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
namespace piko.VulkanMemoryAllocator;
public static unsafe partial class VMA
{
    [StructLayout(LayoutKind.Sequential)]
    public unsafe struct VulkanFunctions
    {
        public IntPtr VkGetInstanceProcAddr;
        public IntPtr VkGetDeviceProcAddr;
        public IntPtr VkGetPhysicalDeviceProperties;
        public IntPtr VkGetPhysicalDeviceMemoryProperties;
        public IntPtr VkAllocateMemory;
        public IntPtr VkFreeMemory;
        public IntPtr VkMapMemory;
        public IntPtr VkUnmapMemory;
        public IntPtr VkFlushMappedMemoryRanges;
        public IntPtr VkInvalidateMappedMemoryRanges;
        public IntPtr VkBindBufferMemory;
        public IntPtr VkBindImageMemory;
        public IntPtr VkGetBufferMemoryRequirements;
        public IntPtr VkGetImageMemoryRequirements;
        public IntPtr VkCreateBuffer;
        public IntPtr VkDestroyBuffer;
        public IntPtr VkCreateImage;
        public IntPtr VkDestroyImage;
        public IntPtr VkCmdCopyBuffer;
        public IntPtr VkGetBufferMemoryRequirements2KHR;
        public IntPtr VkGetImageMemoryRequirements2KHR;
        public IntPtr VkBindBufferMemory2KHR;
        public IntPtr VkBindImageMemory2KHR;
        public IntPtr VkGetPhysicalDeviceMemoryProperties2KHR;
        public IntPtr VkGetDeviceBufferMemoryRequirements;
        public IntPtr VkGetDeviceImageMemoryRequirements;
        public void* VkGetMemoryWin32HandleKHR;
        public IntPtr VkGetPhysicalDeviceProperties2KHR;
    
        public VulkanFunctions(IntPtr vkGetInstanceProcAddr, IntPtr vkGetDeviceProcAddr, IntPtr vkGetPhysicalDeviceProperties, IntPtr vkGetPhysicalDeviceMemoryProperties, IntPtr vkAllocateMemory, IntPtr vkFreeMemory, IntPtr vkMapMemory, IntPtr vkUnmapMemory, IntPtr vkFlushMappedMemoryRanges, IntPtr vkInvalidateMappedMemoryRanges, IntPtr vkBindBufferMemory, IntPtr vkBindImageMemory, IntPtr vkGetBufferMemoryRequirements, IntPtr vkGetImageMemoryRequirements, IntPtr vkCreateBuffer, IntPtr vkDestroyBuffer, IntPtr vkCreateImage, IntPtr vkDestroyImage, IntPtr vkCmdCopyBuffer, IntPtr vkGetBufferMemoryRequirements2KHR, IntPtr vkGetImageMemoryRequirements2KHR, IntPtr vkBindBufferMemory2KHR, IntPtr vkBindImageMemory2KHR, IntPtr vkGetPhysicalDeviceMemoryProperties2KHR, IntPtr vkGetDeviceBufferMemoryRequirements, IntPtr vkGetDeviceImageMemoryRequirements, void* vkGetMemoryWin32HandleKHR, IntPtr vkGetPhysicalDeviceProperties2KHR)
        {
            this.VkGetInstanceProcAddr = vkGetInstanceProcAddr;
            this.VkGetDeviceProcAddr = vkGetDeviceProcAddr;
            this.VkGetPhysicalDeviceProperties = vkGetPhysicalDeviceProperties;
            this.VkGetPhysicalDeviceMemoryProperties = vkGetPhysicalDeviceMemoryProperties;
            this.VkAllocateMemory = vkAllocateMemory;
            this.VkFreeMemory = vkFreeMemory;
            this.VkMapMemory = vkMapMemory;
            this.VkUnmapMemory = vkUnmapMemory;
            this.VkFlushMappedMemoryRanges = vkFlushMappedMemoryRanges;
            this.VkInvalidateMappedMemoryRanges = vkInvalidateMappedMemoryRanges;
            this.VkBindBufferMemory = vkBindBufferMemory;
            this.VkBindImageMemory = vkBindImageMemory;
            this.VkGetBufferMemoryRequirements = vkGetBufferMemoryRequirements;
            this.VkGetImageMemoryRequirements = vkGetImageMemoryRequirements;
            this.VkCreateBuffer = vkCreateBuffer;
            this.VkDestroyBuffer = vkDestroyBuffer;
            this.VkCreateImage = vkCreateImage;
            this.VkDestroyImage = vkDestroyImage;
            this.VkCmdCopyBuffer = vkCmdCopyBuffer;
            this.VkGetBufferMemoryRequirements2KHR = vkGetBufferMemoryRequirements2KHR;
            this.VkGetImageMemoryRequirements2KHR = vkGetImageMemoryRequirements2KHR;
            this.VkBindBufferMemory2KHR = vkBindBufferMemory2KHR;
            this.VkBindImageMemory2KHR = vkBindImageMemory2KHR;
            this.VkGetPhysicalDeviceMemoryProperties2KHR = vkGetPhysicalDeviceMemoryProperties2KHR;
            this.VkGetDeviceBufferMemoryRequirements = vkGetDeviceBufferMemoryRequirements;
            this.VkGetDeviceImageMemoryRequirements = vkGetDeviceImageMemoryRequirements;
            this.VkGetMemoryWin32HandleKHR = vkGetMemoryWin32HandleKHR;
            this.VkGetPhysicalDeviceProperties2KHR = vkGetPhysicalDeviceProperties2KHR;
        }
    }
}
