// Generated by piko.Generator
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
namespace piko.SDL3;
public static unsafe partial class SDL
{
    [StructLayout(LayoutKind.Sequential)]
    public unsafe struct AsyncIOOutcome
    {
        public AsyncIO Asyncio;
        public AsyncIOTaskType Type;
        public AsyncIOResult Result;
        public void* Buffer;
        public ulong Offset;
        public ulong BytesRequested;
        public ulong BytesTransferred;
        public void* Userdata;
    
        public AsyncIOOutcome(AsyncIO asyncio, AsyncIOTaskType type, AsyncIOResult result, void* buffer, ulong offset, ulong bytesRequested, ulong bytesTransferred, void* userdata)
        {
            this.Asyncio = asyncio;
            this.Type = type;
            this.Result = result;
            this.Buffer = buffer;
            this.Offset = offset;
            this.BytesRequested = bytesRequested;
            this.BytesTransferred = bytesTransferred;
            this.Userdata = userdata;
        }
    }
}
