// Generated by piko.Generator
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
namespace piko.SDL3;
public static unsafe partial class SDL
{
    [StructLayout(LayoutKind.Sequential)]
    public unsafe struct AudioDeviceEvent
    {
        public EventType Type;
        public uint Reserved;
        public ulong Timestamp;
        public uint Which;
        public bool Recording;
        public byte Padding1;
        public byte Padding2;
        public byte Padding3;
    
        public AudioDeviceEvent(EventType type, uint reserved, ulong timestamp, uint which, bool recording, byte padding1, byte padding2, byte padding3)
        {
            this.Type = type;
            this.Reserved = reserved;
            this.Timestamp = timestamp;
            this.Which = which;
            this.Recording = recording;
            this.Padding1 = padding1;
            this.Padding2 = padding2;
            this.Padding3 = padding3;
        }
    }
}
