// Generated by piko.Generator
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
namespace piko.SDL3;
public static unsafe partial class SDL
{
    public enum BlendMode : uint
    {
        None = 0x00000000U,
        Blend = 0x00000001U,
        BlendPremultiplied = 0x00000010U,
        Add = 0x00000002U,
        AddPremultiplied = 0x00000020U,
        Mod = 0x00000004U,
        Mul = 0x00000008U,
        Invalid = 0x7FFFFFFFU,
    }
}
