// Generated by piko.Generator
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
namespace piko.SDL3;
public static unsafe partial class SDL
{
    public enum Capitalization : uint
    {
        None,
        Sentences,
        Words,
        Letters,
    }
}
