// Generated by piko.Generator
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
namespace piko.SDL3;
public static unsafe partial class SDL
{
    [StructLayout(LayoutKind.Sequential)]
    public unsafe struct ClipboardEvent
    {
        public EventType Type;
        public uint Reserved;
        public ulong Timestamp;
        public bool Owner;
        public int NumMimeTypes;
        public sbyte** MimeTypes;
    
        public ClipboardEvent(EventType type, uint reserved, ulong timestamp, bool owner, int numMimeTypes, sbyte** mimeTypes)
        {
            this.Type = type;
            this.Reserved = reserved;
            this.Timestamp = timestamp;
            this.Owner = owner;
            this.NumMimeTypes = numMimeTypes;
            this.MimeTypes = mimeTypes;
        }
    }
}
