// Generated by piko.Generator
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
namespace piko.SDL3;
public static unsafe partial class SDL
{
    public enum ColorType : uint
    {
        Unknown = 0,
        Rgb = 1,
        Ycbcr = 2,
    }
}
