// Generated by piko.Generator
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
namespace piko.SDL3;
public static unsafe partial class SDL
{
    [StructLayout(LayoutKind.Sequential)]
    public unsafe struct CommonEvent
    {
        public uint Type;
        public uint Reserved;
        public ulong Timestamp;
    
        public CommonEvent(uint type, uint reserved, ulong timestamp)
        {
            this.Type = type;
            this.Reserved = reserved;
            this.Timestamp = timestamp;
        }
    }
}
