// Generated by piko.Generator
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
namespace piko.SDL3;
public static unsafe partial class SDL
{
    [Flags]
    public enum GLContextReleaseFlag : int
    {
        None = 0x0000,
        Flush = 0x0001,
    }
}
