// Generated by piko.Generator
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
namespace piko.SDL3;
public static unsafe partial class SDL
{
    [Flags]
    public enum GLContextFlag : int
    {
        DebugFlag = 0x0001,
        ForwardCompatibleFlag = 0x0002,
        RobustAccessFlag = 0x0004,
    }
}
