// Generated by piko.Generator
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
namespace piko.SDL3;
public static unsafe partial class SDL
{
    public enum GLContextResetNotification : int
    {
        IsolationFlag = 0x0008,
        NoNotification = 0x0000,
        LoseContext = 0x0001,
    }
}
