// Generated by piko.Generator
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
namespace piko.SDL3;
public static unsafe partial class SDL
{
    [Flags]
    public enum GLProfile : int
    {
        Core = 0x0001,
        Compatibility = 0x0002,
        Es = 0x0004,
    }
}
