// Generated by piko.Generator
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
namespace piko.SDL3;
public static unsafe partial class SDL
{
    [Flags]
    public enum GPUBufferUsageFlags : uint
    {
        Vertex = (1U << 0),
        Index = (1U << 1),
        Indirect = (1U << 2),
        GraphicsStorageRead = (1U << 3),
        ComputeStorageRead = (1U << 4),
        ComputeStorageWrite = (1U << 5),
    }
}
