// Generated by piko.Generator
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
namespace piko.SDL3;
public static unsafe partial class SDL
{
    public enum GPUSampleCount : uint
    {
        Count1,
        Count2,
        Count4,
        Count8,
    }
}
