// Generated by piko.Generator
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
namespace piko.SDL3;
public static unsafe partial class SDL
{
    [StructLayout(LayoutKind.Sequential)]
    public unsafe struct GUID
    {
        public byte Data;
    
        public GUID(byte data)
        {
            this.Data = data;
        }
    }
}
