// Generated by piko.Generator
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
namespace piko.SDL3;
public static unsafe partial class SDL
{
    public enum HitTestResult : uint
    {
        Normal,
        Draggable,
        ResizeTopleft,
        ResizeTop,
        ResizeTopright,
        ResizeRight,
        ResizeBottomright,
        ResizeBottom,
        ResizeBottomleft,
        ResizeLeft,
    }
}
