// Generated by piko.Generator
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
namespace piko.SDL3;
public static unsafe partial class SDL
{
    [StructLayout(LayoutKind.Sequential)]
    public unsafe struct InitState
    {
        public AtomicInt Status;
        public ulong Thread;
        public nint Reserved;
    
        public InitState(AtomicInt status, ulong thread, nint reserved)
        {
            this.Status = status;
            this.Thread = thread;
            this.Reserved = reserved;
        }
    }
}
