// Generated by piko.Generator
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
namespace piko.SDL3;
public static unsafe partial class SDL
{
    [StructLayout(LayoutKind.Sequential)]
    public unsafe struct IOStreamInterface
    {
        public uint Version;
        public IntPtr Size;
        public IntPtr Seek;
        public IntPtr Read;
        public IntPtr Write;
        public IntPtr Flush;
        public IntPtr Close;
    
        public IOStreamInterface(uint version, IntPtr size, IntPtr seek, IntPtr read, IntPtr write, IntPtr flush, IntPtr close)
        {
            this.Version = version;
            this.Size = size;
            this.Seek = seek;
            this.Read = read;
            this.Write = write;
            this.Flush = flush;
            this.Close = close;
        }
    }
}
