// Generated by piko.Generator
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
namespace piko.SDL3;
public static unsafe partial class SDL
{
    [StructLayout(LayoutKind.Sequential)]
    public unsafe struct JoyHatEvent
    {
        public EventType Type;
        public uint Reserved;
        public ulong Timestamp;
        public uint Which;
        public byte Hat;
        public byte Value;
        public byte Padding1;
        public byte Padding2;
    
        public JoyHatEvent(EventType type, uint reserved, ulong timestamp, uint which, byte hat, byte value, byte padding1, byte padding2)
        {
            this.Type = type;
            this.Reserved = reserved;
            this.Timestamp = timestamp;
            this.Which = which;
            this.Hat = hat;
            this.Value = value;
            this.Padding1 = padding1;
            this.Padding2 = padding2;
        }
    }
}
