// Generated by piko.Generator
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
namespace piko.SDL3;
public static unsafe partial class SDL
{
    public enum Keymod : ushort
    {
        None = 0x0000,
        Lshift = 0x0001,
        Rshift = 0x0002,
        Level5 = 0x0004,
        Lctrl = 0x0040,
        Rctrl = 0x0080,
        Lalt = 0x0100,
        Ralt = 0x0200,
        Lgui = 0x0400,
        Rgui = 0x0800,
        Num = 0x1000,
        Caps = 0x2000,
        Mode = 0x4000,
        Scroll = 0x8000,
        Ctrl = (0x0040 | 0x0080),
        Shift = (0x0001 | 0x0002),
        Alt = (0x0100 | 0x0200),
        Gui = (0x0400 | 0x0800),
    }
}
