// Generated by piko.Generator
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
namespace piko.SDL3;
public static unsafe partial class SDL
{
    [Flags]
    public enum Keymod : uint
    {
        None = 0x0000U,
        Lshift = 0x0001U,
        Rshift = 0x0002U,
        Level5 = 0x0004U,
        Lctrl = 0x0040U,
        Rctrl = 0x0080U,
        Lalt = 0x0100U,
        Ralt = 0x0200U,
        Lgui = 0x0400U,
        Rgui = 0x0800U,
        Num = 0x1000U,
        Caps = 0x2000U,
        Mode = 0x4000U,
        Scroll = 0x8000U,
        Ctrl = (0x0040U | 0x0080U),
        Shift = (0x0001U | 0x0002U),
        Alt = (0x0100U | 0x0200U),
        Gui = (0x0400U | 0x0800U),
    }
}
