// Generated by piko.Generator
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
namespace piko.SDL3;
public static unsafe partial class SDL
{
    public enum MatrixCoefficients : uint
    {
        Identity = 0,
        Bt709 = 1,
        Unspecified = 2,
        Fcc = 4,
        Bt470bg = 5,
        Bt601 = 6,
        Smpte240 = 7,
        Ycgco = 8,
        Bt2020Ncl = 9,
        Bt2020Cl = 10,
        Smpte2085 = 11,
        ChromaDerivedNcl = 12,
        ChromaDerivedCl = 13,
        Ictcp = 14,
        Custom = 31,
    }
}
