// Generated by piko.Generator
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
namespace piko.SDL3;
public static unsafe partial class SDL
{
    [StructLayout(LayoutKind.Sequential)]
    public unsafe struct MessageBoxColorScheme
    {
        public MessageBoxColor Colors;
    
        public MessageBoxColorScheme(MessageBoxColor colors)
        {
            this.Colors = colors;
        }
    }
}
