// Generated by piko.Generator
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
namespace piko.SDL3;
public static unsafe partial class SDL
{
    [Flags]
    public enum MessageBoxFlags : uint
    {
        Error = 0x00000010U,
        Warning = 0x00000020U,
        Information = 0x00000040U,
        ButtonsLeftToRight = 0x00000080U,
        ButtonsRightToLeft = 0x00000100U,
        ButtonReturnkeyDefault = 0x00000001U,
        ButtonEscapekeyDefault = 0x00000002U,
    }
}
