// Generated by piko.Generator
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
namespace piko.SDL3;
public static unsafe partial class SDL
{
    [StructLayout(LayoutKind.Sequential)]
    public unsafe struct MouseMotionEvent
    {
        public EventType Type;
        public uint Reserved;
        public ulong Timestamp;
        public uint WindowID;
        public uint Which;
        public MouseButtonFlags State;
        public float X;
        public float Y;
        public float Xrel;
        public float Yrel;
    
        public MouseMotionEvent(EventType type, uint reserved, ulong timestamp, uint windowID, uint which, MouseButtonFlags state, float x, float y, float xrel, float yrel)
        {
            this.Type = type;
            this.Reserved = reserved;
            this.Timestamp = timestamp;
            this.WindowID = windowID;
            this.Which = which;
            this.State = state;
            this.X = x;
            this.Y = y;
            this.Xrel = xrel;
            this.Yrel = yrel;
        }
    }
}
