// Generated by piko.Generator
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
namespace piko.SDL3;
public static unsafe partial class SDL
{
    [Flags]
    public enum MouseButtonFlags : uint
    {
        Left = 1,
        Middle = 2,
        Right = 3,
        X1 = 4,
        X2 = 5,
        Lmask = (1U << ((1) - 1)),
        Mmask = (1U << ((2) - 1)),
        Rmask = (1U << ((3) - 1)),
        X1mask = (1U << ((4) - 1)),
        X2mask = (1U << ((5) - 1)),
    }
}
