// Generated by piko.Generator
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
namespace piko.SDL3;
public static unsafe partial class SDL
{
    [Flags]
    public enum PenInputFlags : uint
    {
        Down = (1U << 0),
        Button1 = (1U << 1),
        Button2 = (1U << 2),
        Button3 = (1U << 3),
        Button4 = (1U << 4),
        Button5 = (1U << 5),
        EraserTip = (1U << 30),
        InProximity = (1U << 31),
    }
}
