// Generated by piko.Generator
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
namespace piko.SDL3;
public static unsafe partial class SDL
{
    [StructLayout(LayoutKind.Sequential)]
    public unsafe struct PenMotionEvent
    {
        public EventType Type;
        public uint Reserved;
        public ulong Timestamp;
        public uint WindowID;
        public uint Which;
        public PenInputFlags PenState;
        public float X;
        public float Y;
    
        public PenMotionEvent(EventType type, uint reserved, ulong timestamp, uint windowID, uint which, PenInputFlags penState, float x, float y)
        {
            this.Type = type;
            this.Reserved = reserved;
            this.Timestamp = timestamp;
            this.WindowID = windowID;
            this.Which = which;
            this.PenState = penState;
            this.X = x;
            this.Y = y;
        }
    }
}
