// Generated by piko.Generator
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
namespace piko.SDL3;
public static unsafe partial class SDL
{
    public enum PropertyType : uint
    {
        Invalid,
        Pointer,
        String,
        Number,
        Float,
        Boolean,
    }
}
