// Generated by piko.Generator
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
namespace piko.SDL3;
public static unsafe partial class SDL
{
    public enum Sandbox : uint
    {
        None = 0,
        UnknownContainer,
        Flatpak,
        Snap,
        Macos,
    }
}
