// Generated by piko.Generator
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
namespace piko.SDL3;
public static unsafe partial class SDL
{
    [StructLayout(LayoutKind.Sequential)]
    public unsafe struct StorageInterface
    {
        public uint Version;
        public IntPtr Close;
        public IntPtr Ready;
        public IntPtr Enumerate;
        public IntPtr Info;
        public IntPtr ReadFile;
        public IntPtr WriteFile;
        public IntPtr Mkdir;
        public IntPtr Remove;
        public IntPtr Rename;
        public IntPtr Copy;
        public IntPtr SpaceRemaining;
    
        public StorageInterface(uint version, IntPtr close, IntPtr ready, IntPtr enumerate, IntPtr info, IntPtr readFile, IntPtr writeFile, IntPtr mkdir, IntPtr remove, IntPtr rename, IntPtr copy, IntPtr spaceRemaining)
        {
            this.Version = version;
            this.Close = close;
            this.Ready = ready;
            this.Enumerate = enumerate;
            this.Info = info;
            this.ReadFile = readFile;
            this.WriteFile = writeFile;
            this.Mkdir = mkdir;
            this.Remove = remove;
            this.Rename = rename;
            this.Copy = copy;
            this.SpaceRemaining = spaceRemaining;
        }
    }
}
