// Generated by piko.Generator
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
namespace piko.SDL3;
public static unsafe partial class SDL
{
    [StructLayout(LayoutKind.Sequential)]
    public unsafe struct Surface
    {
        public uint Flags;
        public PixelFormat Format;
        public int W;
        public int H;
        public int Pitch;
        public nint Pixels;
        public int Refcount;
        public nint Reserved;
    
        public Surface(uint flags, PixelFormat format, int w, int h, int pitch, nint pixels, int refcount, nint reserved)
        {
            this.Flags = flags;
            this.Format = format;
            this.W = w;
            this.H = h;
            this.Pitch = pitch;
            this.Pixels = pixels;
            this.Refcount = refcount;
            this.Reserved = reserved;
        }
    }
}
