// Generated by piko.Generator
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
namespace piko.SDL3;
public static unsafe partial class SDL
{
    public enum SystemCursor : uint
    {
        Default,
        Text,
        Wait,
        Crosshair,
        Progress,
        NwseResize,
        NeswResize,
        EwResize,
        NsResize,
        Move,
        NotAllowed,
        Pointer,
        NwResize,
        NResize,
        NeResize,
        EResize,
        SeResize,
        SResize,
        SwResize,
        WResize,
        Count,
    }
}
