// Generated by piko.Generator
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
namespace piko.SDL3;
public static unsafe partial class SDL
{
    [StructLayout(LayoutKind.Sequential)]
    public unsafe struct TextureRef
    {
        public PixelFormat Format;
        public int W;
        public int H;
        public int Refcount;
    
        public TextureRef(PixelFormat format, int w, int h, int refcount)
        {
            this.Format = format;
            this.W = w;
            this.H = h;
            this.Refcount = refcount;
        }
    }
}
