// Generated by piko.Generator
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
namespace piko.SDL3;
public static unsafe partial class SDL
{
    public enum TransferCharacteristics : uint
    {
        Unknown = 0,
        Bt709 = 1,
        Unspecified = 2,
        Gamma22 = 4,
        Gamma28 = 5,
        Bt601 = 6,
        Smpte240 = 7,
        Linear = 8,
        Log100 = 9,
        Log100Sqrt10 = 10,
        Iec61966 = 11,
        Bt1361 = 12,
        Srgb = 13,
        Bt202010bit = 14,
        Bt202012bit = 15,
        Pq = 16,
        Smpte428 = 17,
        Hlg = 18,
        Custom = 31,
    }
}
