using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using piko.Generator;
using piko.Generator.Analyzers;
using piko.Generator.Bindings;
using piko.Generator.Configs;

if (args.Length == 0)
{
    Console.WriteLine("You must specify a config file!");
    return;
}

string jsonFilePath = Path.GetFullPath(args[0]);
string workingDir = Path.GetDirectoryName(jsonFilePath);
string jsonText = File.ReadAllText(jsonFilePath);
PikoGeneratorConfig pikoConfig = JsonSerializer.Deserialize<PikoGeneratorConfig>(jsonText, new JsonSerializerOptions
{
    IncludeFields = true,
    ReadCommentHandling = JsonCommentHandling.Skip,
    AllowTrailingCommas = true,
    Converters = { new JsonStringEnumConverter() }
});

ClangSharpAnalyzer sdl3Anaylyzer = new ClangSharpAnalyzer(workingDir, pikoConfig.ClangSharp, pikoConfig.TypeRemapping.Keys.ToList());
BindingsSet sdl3Bindings = sdl3Anaylyzer.Analyze();
NamePrettifier prettifier = new NamePrettifier(new NamePrettifier.Options
{
    PrefixToStrip = pikoConfig.PrefixToStrip,
    EnumPrefixRemapping = pikoConfig.Enums.CustomPrefixes,
    EnumPrefixStrip = pikoConfig.Enums.PrefixesToStrip,
    ConstantPrefixRemapping = pikoConfig.Constants.PrefixRemapping,
    ConstantPrefixStrip = pikoConfig.Constants.AssociateConstantPrefixWithType.Keys.ToList(),
    NameRemapping = pikoConfig.TypeRemapping.ToDictionary(remap => remap.Key, remap => remap.Value.Name)
});
prettifier.Prettify(ref sdl3Bindings);

TypeTransformer transformer = new TypeTransformer(new TypeTransformer.Options
{
    EmptyStructsAreHandleTypes = pikoConfig.Generator.EmptyStructsAreHandleTypes,
    BytesAreBooleansByDefault = pikoConfig.Generator.BytesAreBooleans,
    AssociateConstantPrefixWithType = pikoConfig.Constants.AssociateConstantPrefixWithType,
    TypeRemapping = pikoConfig.TypeRemapping
});
transformer.Transform(ref sdl3Bindings);

Generator generator = new Generator(sdl3Bindings, pikoConfig.MethodClassName, new Generator.Options
{
    LibraryDllName = pikoConfig.LibraryDllName,
    UseLibraryImport = pikoConfig.Generator.UseLibraryImport,
    AllTypesAreSubTypes = pikoConfig.Generator.AllTypesAreSubTypes,
    HandleTypesUseIHandleInterface = pikoConfig.Generator.HandleTypesUseIHandleInterface,
    AllStringsAreUTF8 = pikoConfig.Generator.AllStringsAreUTF8,
    CustomReturnValueTypeMarshallers = pikoConfig.Generator.CustomReturnValueTypeMarshallers
});
Generator.Output[] outputs = generator.Generate();

StringBuilder sb = new StringBuilder();

string sdl3Output = Path.Combine(workingDir, pikoConfig.OutputDirectory);
foreach (Generator.Output output in outputs)
{
    /*Console.WriteLine($"{output.TypeName}.cs");
    Console.WriteLine("=====================================================================");
    Console.WriteLine(output.Code);
    Console.WriteLine();*/

    sb.Clear();
    sb.AppendLine("// Generated by piko.Generator"); // this watermark will be used to determine which files to delete when starting the generator
    sb.AppendLine("using System.Runtime.InteropServices;");
    sb.AppendLine("using System.Runtime.InteropServices.Marshalling;");
    sb.AppendLine($"namespace {pikoConfig.Namespace};");
    sb.Append(output.Code);

    string filePath = Path.Combine(sdl3Output, $"{output.TypeName}.cs");
    File.WriteAllText(filePath, sb.ToString());
}