<Project>
    <PropertyGroup>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <RepositoryUrl>https://github.com/aquagoose/piko</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <Authors>aquagoose</Authors>
        <PackageTags>sdl3;sdl;graphics;opengl;vulkan;directx</PackageTags>
        <PackageLicenseFile>LICENSE</PackageLicenseFile>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageIcon>icon.png</PackageIcon>
        <Version>0.0.3.1</Version>
    </PropertyGroup>

    <ItemGroup>
        <None Include="$(SolutionDir)LICENSE" Pack="true" PackagePath="" />
        <None Include="$(SolutionDir)README.md" Pack="true" PackagePath="" />
        <None Include="$(SolutionDir)icon.png" Pack="true" PackagePath="" />
    </ItemGroup>
</Project>