<Project>
    <PropertyGroup>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <RepositoryUrl>https://github.com/aquagoose/piko</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <Authors>aquagoose</Authors>
        <PackageTags>sdl3;sdl;graphics;opengl;vulkan;directx</PackageTags>
        <PackageLicenseFile>LICENSE</PackageLicenseFile>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageIcon>piko.png</PackageIcon>
        <Version>0.0.4</Version>
        <Description>A small n cute set of gamedev-focused bindings for C#.</Description>
    </PropertyGroup>

    <ItemGroup>
        <None Include="$(SolutionDir)LICENSE" Pack="true" PackagePath="" />
        <None Include="$(SolutionDir)README.md" Pack="true" PackagePath="" />
        <None Include="$(SolutionDir)piko.png" Pack="true" PackagePath="" />
    </ItemGroup>
</Project>