// Generated by piko.Generator
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
namespace piko.SDL3.ShaderCross;
public static unsafe partial class SDLShaderCross
{
    [StructLayout(LayoutKind.Sequential)]
    public unsafe struct ComputePipelineMetadata
    {
        public uint NumSamplers;
        public uint NumReadonlyStorageTextures;
        public uint NumReadonlyStorageBuffers;
        public uint NumReadwriteStorageTextures;
        public uint NumReadwriteStorageBuffers;
        public uint NumUniformBuffers;
        public uint ThreadcountX;
        public uint ThreadcountY;
        public uint ThreadcountZ;
    
        public ComputePipelineMetadata(uint numSamplers, uint numReadonlyStorageTextures, uint numReadonlyStorageBuffers, uint numReadwriteStorageTextures, uint numReadwriteStorageBuffers, uint numUniformBuffers, uint threadcountX, uint threadcountY, uint threadcountZ)
        {
            this.NumSamplers = numSamplers;
            this.NumReadonlyStorageTextures = numReadonlyStorageTextures;
            this.NumReadonlyStorageBuffers = numReadonlyStorageBuffers;
            this.NumReadwriteStorageTextures = numReadwriteStorageTextures;
            this.NumReadwriteStorageBuffers = numReadwriteStorageBuffers;
            this.NumUniformBuffers = numUniformBuffers;
            this.ThreadcountX = threadcountX;
            this.ThreadcountY = threadcountY;
            this.ThreadcountZ = threadcountZ;
        }
    }
}
