// Generated by piko.Generator
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
namespace piko.SDL3.ShaderCross;
public static unsafe partial class SDLShaderCross
{
    [StructLayout(LayoutKind.Sequential)]
    public unsafe struct GraphicsShaderResourceInfo
    {
        public uint NumSamplers;
        public uint NumStorageTextures;
        public uint NumStorageBuffers;
        public uint NumUniformBuffers;
    
        public GraphicsShaderResourceInfo(uint numSamplers, uint numStorageTextures, uint numStorageBuffers, uint numUniformBuffers)
        {
            this.NumSamplers = numSamplers;
            this.NumStorageTextures = numStorageTextures;
            this.NumStorageBuffers = numStorageBuffers;
            this.NumUniformBuffers = numUniformBuffers;
        }
    }
}
