// Generated by piko.Generator
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
namespace piko.SDL3.ShaderCross;
public static unsafe partial class SDLShaderCross
{
    [StructLayout(LayoutKind.Sequential)]
    public unsafe struct GraphicsShaderMetadata
    {
        public GraphicsShaderResourceInfo ResourceInfo;
        public uint NumInputs;
        public IOVarMetadata* Inputs;
        public uint NumOutputs;
        public IOVarMetadata* Outputs;
    
        public GraphicsShaderMetadata(GraphicsShaderResourceInfo resourceInfo, uint numInputs, IOVarMetadata* inputs, uint numOutputs, IOVarMetadata* outputs)
        {
            this.ResourceInfo = resourceInfo;
            this.NumInputs = numInputs;
            this.Inputs = inputs;
            this.NumOutputs = numOutputs;
            this.Outputs = outputs;
        }
    }
}
