// Generated by piko.Generator
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
namespace piko.SDL3.ShaderCross;
public static unsafe partial class SDLShaderCross
{
    [StructLayout(LayoutKind.Sequential)]
    public unsafe struct HLSLInfo
    {
        public sbyte* Source;
        public sbyte* Entrypoint;
        public sbyte* IncludeDir;
        public HLSLDefine* Defines;
        public ShaderStage ShaderStage;
        public uint Props;
    
        public HLSLInfo(sbyte* source, sbyte* entrypoint, sbyte* includeDir, HLSLDefine* defines, ShaderStage shaderStage, uint props)
        {
            this.Source = source;
            this.Entrypoint = entrypoint;
            this.IncludeDir = includeDir;
            this.Defines = defines;
            this.ShaderStage = shaderStage;
            this.Props = props;
        }
    }
}
