// Generated by piko.Generator
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
namespace piko.SDL3.ShaderCross;
public static unsafe partial class SDLShaderCross
{
    [StructLayout(LayoutKind.Sequential)]
    public unsafe struct HLSLDefine
    {
        public sbyte* Name;
        public sbyte* Value;
    
        public HLSLDefine(sbyte* name, sbyte* value)
        {
            this.Name = name;
            this.Value = value;
        }
    }
}
