// Generated by piko.Generator
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
namespace piko.SDL3.ShaderCross;
public static unsafe partial class SDLShaderCross
{
    public enum IOVarType : uint
    {
        Unknown,
        Int8,
        Uint8,
        Int16,
        Uint16,
        Int32,
        Uint32,
        Int64,
        Uint64,
        Float16,
        Float32,
        Float64,
    }
}
