// Generated by piko.Generator
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
namespace piko.SDL3.ShaderCross;
public static unsafe partial class SDLShaderCross
{
    [StructLayout(LayoutKind.Sequential)]
    public unsafe struct IOVarMetadata
    {
        public sbyte* Name;
        public uint Location;
        public IOVarType VectorType;
        public uint VectorSize;
    
        public IOVarMetadata(sbyte* name, uint location, IOVarType vectorType, uint vectorSize)
        {
            this.Name = name;
            this.Location = location;
            this.VectorType = vectorType;
            this.VectorSize = vectorSize;
        }
    }
}
