<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <Description>A small n cute set of actually good* SDL3_shadercross bindings.</Description>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\piko.Core\piko.Core.csproj" />
      <ProjectReference Include="..\piko.SDL3\piko.SDL3.csproj" />
    </ItemGroup>

</Project>
