// Generated by piko.Generator
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
namespace piko.SDL3.ShaderCross;
public static unsafe partial class SDLShaderCross
{
    public static unsafe partial class Prop
    {
        public const string ShaderDebugEnableBoolean = "SDL_shadercross.spirv.debug.enable";
        public const string ShaderDebugNameString = "SDL_shadercross.spirv.debug.name";
        public const string ShaderCullUnusedBindingsBoolean = "SDL_shadercross.spirv.cull_unused_bindings";
        public const string SpirvPsslCompatibilityBoolean = "SDL_shadercross.spirv.pssl.compatibility";
        public const string SpirvMslVersionString = "SDL_shadercross.spirv.msl.version";
        public const string HlslSkipSpirvRoundtripBoolean = "SDL_shadercross.hlsl.skip_spirv_roundtrip";
    }
    
}
