// Generated by piko.Generator
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
namespace piko.SDL3.ShaderCross;
public static unsafe partial class SDLShaderCross
{
    public const string LibraryName = "SDL3_shadercross";

    public const int MajorVersion = 3;
    public const int MinorVersion = 0;
    public const int MicroVersion = 0;

    [LibraryImport(LibraryName, EntryPoint = "SDL_ShaderCross_Init", StringMarshalling = StringMarshalling.Utf8)]
    [return: MarshalAs(UnmanagedType.I1)]
    public static partial bool Init();

    [LibraryImport(LibraryName, EntryPoint = "SDL_ShaderCross_Quit", StringMarshalling = StringMarshalling.Utf8)]
    public static partial void Quit();

    [LibraryImport(LibraryName, EntryPoint = "SDL_ShaderCross_GetSPIRVShaderFormats", StringMarshalling = StringMarshalling.Utf8)]
    public static partial SDL.GPUShaderFormat GetSPIRVShaderFormats();

    [LibraryImport(LibraryName, EntryPoint = "SDL_ShaderCross_TranspileMSLFromSPIRV", StringMarshalling = StringMarshalling.Utf8)]
    public static partial nint TranspileMSLFromSPIRV(SPIRVInfo* info);

    [LibraryImport(LibraryName, EntryPoint = "SDL_ShaderCross_TranspileHLSLFromSPIRV", StringMarshalling = StringMarshalling.Utf8)]
    public static partial nint TranspileHLSLFromSPIRV(SPIRVInfo* info);

    [LibraryImport(LibraryName, EntryPoint = "SDL_ShaderCross_CompileDXBCFromSPIRV", StringMarshalling = StringMarshalling.Utf8)]
    public static partial nint CompileDXBCFromSPIRV(SPIRVInfo* info, nuint* size);

    [LibraryImport(LibraryName, EntryPoint = "SDL_ShaderCross_CompileDXILFromSPIRV", StringMarshalling = StringMarshalling.Utf8)]
    public static partial nint CompileDXILFromSPIRV(SPIRVInfo* info, nuint* size);

    [LibraryImport(LibraryName, EntryPoint = "SDL_ShaderCross_CompileGraphicsShaderFromSPIRV", StringMarshalling = StringMarshalling.Utf8)]
    public static partial nint CompileGraphicsShaderFromSPIRV(nint device, SPIRVInfo* info, GraphicsShaderResourceInfo* resourceInfo, uint props);

    [LibraryImport(LibraryName, EntryPoint = "SDL_ShaderCross_CompileComputePipelineFromSPIRV", StringMarshalling = StringMarshalling.Utf8)]
    public static partial nint CompileComputePipelineFromSPIRV(nint device, SPIRVInfo* info, ComputePipelineMetadata* metadata, uint props);

    [LibraryImport(LibraryName, EntryPoint = "SDL_ShaderCross_ReflectGraphicsSPIRV", StringMarshalling = StringMarshalling.Utf8)]
    public static partial GraphicsShaderMetadata* ReflectGraphicsSPIRV(byte* bytecode, nuint bytecodeSize, uint props);

    [LibraryImport(LibraryName, EntryPoint = "SDL_ShaderCross_ReflectComputeSPIRV", StringMarshalling = StringMarshalling.Utf8)]
    public static partial ComputePipelineMetadata* ReflectComputeSPIRV(byte* bytecode, nuint bytecodeSize, uint props);

    [LibraryImport(LibraryName, EntryPoint = "SDL_ShaderCross_GetHLSLShaderFormats", StringMarshalling = StringMarshalling.Utf8)]
    public static partial SDL.GPUShaderFormat GetHLSLShaderFormats();

    [LibraryImport(LibraryName, EntryPoint = "SDL_ShaderCross_CompileDXBCFromHLSL", StringMarshalling = StringMarshalling.Utf8)]
    public static partial nint CompileDXBCFromHLSL(HLSLInfo* info, nuint* size);

    [LibraryImport(LibraryName, EntryPoint = "SDL_ShaderCross_CompileDXILFromHLSL", StringMarshalling = StringMarshalling.Utf8)]
    public static partial nint CompileDXILFromHLSL(HLSLInfo* info, nuint* size);

    [LibraryImport(LibraryName, EntryPoint = "SDL_ShaderCross_CompileSPIRVFromHLSL", StringMarshalling = StringMarshalling.Utf8)]
    public static partial nint CompileSPIRVFromHLSL(HLSLInfo* info, nuint* size);


}
