// Generated by piko.Generator
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
namespace piko.SDL3.ShaderCross;
public static unsafe partial class SDLShaderCross
{
    public enum ShaderStage : uint
    {
        Vertex,
        Fragment,
        Compute,
    }
}
