// Generated by piko.Generator
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
namespace piko.SDL3.ShaderCross;
public static unsafe partial class SDLShaderCross
{
    [StructLayout(LayoutKind.Sequential)]
    public unsafe struct SPIRVInfo
    {
        public byte* Bytecode;
        public nuint BytecodeSize;
        public sbyte* Entrypoint;
        public ShaderStage ShaderStage;
        public uint Props;
    
        public SPIRVInfo(byte* bytecode, nuint bytecodeSize, sbyte* entrypoint, ShaderStage shaderStage, uint props)
        {
            this.Bytecode = bytecode;
            this.BytecodeSize = bytecodeSize;
            this.Entrypoint = entrypoint;
            this.ShaderStage = shaderStage;
            this.Props = props;
        }
    }
}
